<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ $forced ? 'Set Your Password' : 'Change Password' }} — Museo de Baler</title>
  <link href="https://fonts.googleapis.com/css2?family=Young+Serif&family=Instrument+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
  @vite(['resources/css/app.css'])
  <style>
    body{display:flex;align-items:center;justify-content:center;min-height:100vh;padding:20px}
    .pw-card{background:#fff;border-radius:16px;box-shadow:0 20px 60px rgba(0,0,0,.18);width:100%;max-width:440px;padding:36px 32px}
    .pw-icon{width:46px;height:46px;border-radius:13px;background:linear-gradient(135deg,#16a34a,#22c55e);display:flex;align-items:center;justify-content:center;margin-bottom:20px;box-shadow:0 8px 24px rgba(34,197,94,.25)}
    .pw-icon svg{width:23px;height:23px;color:#fff}
    .pw-card h1{font-size:24px;color:#1a1a1a;margin:0 0 6px;line-height:1.25}
    .pw-card .sub{font-size:13px;color:#6b7280;margin:0 0 24px;line-height:1.6}
    .why{background:#fffbeb;border:1px solid #fde68a;border-radius:10px;padding:12px 14px;margin-bottom:20px;font-size:12.5px;color:#92400e;line-height:1.6}
    .fg{margin-bottom:16px}
    label{display:block;font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:.07em;margin-bottom:6px}
    .pw-wrap{position:relative}
    .pw-wrap input{width:100%;padding:11px 42px 11px 14px;border-radius:9px;border:1.5px solid #e5e7eb;font-size:14px;color:#1a1a1a;background:#fafafa;outline:none;transition:border-color .15s;font-family:'Instrument Sans',sans-serif}
    .pw-wrap input:focus{border-color:#22c55e}
    .pw-toggle{position:absolute;right:10px;top:50%;transform:translateY(-50%);cursor:pointer;color:#9ca3af;background:none;border:none;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;padding:4px 6px}
    .hint{font-size:11.5px;color:#9ca3af;margin-top:6px;line-height:1.55}
    .btn-save{width:100%;background:linear-gradient(135deg,#16a34a,#22c55e);color:#fff;border:none;border-radius:9px;padding:13px;font-family:'Instrument Sans',sans-serif;font-size:14px;font-weight:700;cursor:pointer;box-shadow:0 4px 16px rgba(34,197,94,.28);transition:opacity .15s;margin-top:6px}
    .btn-save:hover{opacity:.9}
    .error-box{color:#b91c1c;font-size:12.5px;margin-bottom:16px;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:11px 14px;line-height:1.6}
    .error-box ul{margin:0;padding-left:16px}
    .foot{margin-top:22px;padding-top:18px;border-top:1px solid #f3f4f6;display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:12px}
    .foot a,.foot button{color:#6b7280;text-decoration:none;background:none;border:none;font-family:'Instrument Sans',sans-serif;font-size:12px;cursor:pointer;padding:0}
    .foot a:hover,.foot button:hover{color:#16a34a}
  </style>
</head>
<body>
<div class="pw-card">
  <div class="pw-icon">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
  </div>

  @if($forced)
    <h1>Set your own password</h1>
    <p class="sub">Signed in as <strong>{{ auth()->user()->name }}</strong> ({{ auth()->user()->email }}).</p>
    <div class="why">
      The password you were given was generated by the Tourism Office and they
      still know it. Until you replace it with one only you know, the activity
      log cannot tell your work apart from theirs. Pick a password now — the
      rest of the system opens up once you do.
    </div>
  @else
    <h1>Change password</h1>
    <p class="sub">Signed in as <strong>{{ auth()->user()->name }}</strong> ({{ auth()->user()->email }}).</p>
  @endif

  @if($errors->any())
    <div class="error-box">
      <ul>
        @foreach($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  <form method="POST" action="{{ route('password.update') }}">
    @csrf
    @method('PUT')

    <div class="fg">
      <label for="current_password">{{ $forced ? 'The password you were given' : 'Current password' }}</label>
      <div class="pw-wrap">
        <input type="password" id="current_password" name="current_password" required autocomplete="current-password" autofocus>
        <button type="button" class="pw-toggle" data-target="current_password">Show</button>
      </div>
    </div>

    <div class="fg">
      <label for="password">New password</label>
      <div class="pw-wrap">
        <input type="password" id="password" name="password" required autocomplete="new-password">
        <button type="button" class="pw-toggle" data-target="password">Show</button>
      </div>
      <p class="hint">{{ $hint }}</p>
    </div>

    <div class="fg">
      <label for="password_confirmation">Repeat new password</label>
      <div class="pw-wrap">
        <input type="password" id="password_confirmation" name="password_confirmation" required autocomplete="new-password">
        <button type="button" class="pw-toggle" data-target="password_confirmation">Show</button>
      </div>
    </div>

    <button type="submit" class="btn-save">{{ $forced ? 'Set password and continue' : 'Change password' }}</button>
  </form>

  <div class="foot">
    @if($forced)
      <span style="color:#9ca3af">Not you?</span>
    @else
      <a href="{{ url()->previous() === url()->current() ? url('/') : url()->previous() }}">Back</a>
    @endif
    <form method="POST" action="{{ route('logout') }}" style="margin:0">
      @csrf
      <button type="submit">Sign out</button>
    </form>
  </div>
</div>

<script>
document.querySelectorAll('.pw-toggle').forEach(function (btn) {
  btn.addEventListener('click', function () {
    var input = document.getElementById(btn.dataset.target);
    var shown = input.type === 'text';
    input.type = shown ? 'password' : 'text';
    btn.textContent = shown ? 'Show' : 'Hide';
  });
});
</script>
</body>
</html>
