<?php

namespace App\Http\Controllers;

use App\Models\AttendanceCorrection;
use App\Models\Log;
use App\Models\Staff;
use App\Models\StaffAttendance;
use App\Models\StaffSchedule;
use App\Services\AttendanceQrService;
use App\Services\AttendanceStatusService;
use App\Services\GeofenceService;
use App\Support\Device;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class StaffAttendanceController extends Controller
{
    /**
     * Gap enforced between a check-in and the check-out that follows it, so a
     * staff member who scans twice by reflex does not close their own day.
     */
    private const MIN_MINUTES_BEFORE_CHECKOUT = 30;

    public function __construct(
        private AttendanceQrService $qr,
        private GeofenceService $geofence,
        private AttendanceStatusService $status,
    ) {}

    // -- Staff room screen -------------------------------------------------
    // Left open on a tablet or spare monitor by the staff entrance. Shows
    // nothing but the rotating code; nobody records attendance from here.

    public function kiosk()
    {
        return view('staff-attendance.kiosk', [
            'rotateSeconds' => AttendanceQrService::WINDOW_SECONDS,
        ]);
    }

    /** The QR image itself. Regenerated by the kiosk page each window. */
    public function kioskQr(Request $request)
    {
        $payload = $this->qr->currentPayload(auth()->id());

        require_once public_path('phpqrcode/phpqrcode.php');

        ob_start();
        \QRcode::png($payload, false, QR_ECLEVEL_M, 10, 2);
        $png = ob_get_clean();

        return response($png, 200, [
            'Content-Type'  => 'image/png',
            // The code is only valid for one window - never let a proxy or the
            // browser hand back a stale image after it has rotated.
            'Cache-Control' => 'no-store, no-cache, must-revalidate',
            'Pragma'        => 'no-cache',
        ]);
    }

    /** Lets the kiosk page line its countdown up with the server's window. */
    public function kioskTick()
    {
        return response()->json([
            'window'     => $this->qr->currentWindow(),
            'expires_in' => $this->qr->secondsUntilRotation(),
        ])->header('Cache-Control', 'no-store');
    }

    // -- Staff member's own phone ------------------------------------------

    public function mine(Request $request)
    {
        $staff = $request->user();
        $today = today();

        $todayRows = StaffAttendance::where('staff_id', $staff->staff_id)
            ->whereDate('work_date', $today)
            ->get();

        $from = $today->copy()->startOfMonth();
        $days = $this->status->rangeFor($staff, $from, $today)->reverse();

        return view('staff-attendance.mine', [
            'today'     => $this->status->summarise($staff, $today, $todayRows),
            'days'      => $days,
            'monthFrom' => $from,
            // The one screen that has to work in both places. On a phone it
            // drops the panel chrome entirely - there is no sidebar to shrink
            // to icons when the sidebar leads nowhere the phone may go.
            'layout'    => Device::isPhone($request->userAgent())
                ? 'layouts.mobile'
                : 'layouts.admin',
            // Shown as a banner when the distance check is off, so a testing
            // switch cannot be mistaken for a working geofence.
            'geofenceOff' => !$this->geofence->enforced(),
        ]);
    }

    /**
     * Records a scan. The QR proves the phone is looking at the museum's
     * screen right now; the session proves who is holding the phone; the
     * geofence proves the phone is on the grounds. All three are required.
     */
    public function scan(Request $request)
    {
        $data = $request->validate([
            'code'      => 'required|string|max:255',
            'latitude'  => 'nullable|numeric|between:-90,90',
            'longitude' => 'nullable|numeric|between:-180,180',
            'accuracy'  => 'nullable|integer|min:0|max:100000',
        ]);

        $staff = $request->user();

        if (!$staff->status) {
            return response()->json(['ok' => false, 'message' => 'This account is deactivated.'], 403);
        }

        if ($reason = $this->qr->verify($data['code'])) {
            return response()->json(['ok' => false, 'message' => $reason], 422);
        }

        $fence = $this->geofence->check(
            isset($data['latitude'])  ? (float) $data['latitude']  : null,
            isset($data['longitude']) ? (float) $data['longitude'] : null,
            $data['accuracy'] ?? null,
        );

        if (!$fence['ok']) {
            return response()->json(['ok' => false, 'message' => $fence['reason']], 422);
        }

        $today    = today();
        $existing = StaffAttendance::where('staff_id', $staff->staff_id)
            ->whereDate('work_date', $today)
            ->get();

        $in  = $existing->firstWhere('type', 'in');
        $out = $existing->firstWhere('type', 'out');

        if ($out) {
            return response()->json([
                'ok'      => false,
                'message' => 'You already checked out at ' . $out->scanned_at->format('g:i A') . '.',
            ], 422);
        }

        $type = $in ? 'out' : 'in';

        if ($type === 'out' && $in->scanned_at->diffInMinutes(now()) < self::MIN_MINUTES_BEFORE_CHECKOUT) {
            return response()->json([
                'ok'      => true,
                'noop'    => true,
                'message' => 'Already checked in at ' . $in->scanned_at->format('g:i A') . '.',
            ]);
        }

        $record = StaffAttendance::create([
            'staff_id'   => $staff->staff_id,
            'work_date'  => $today,
            'type'       => $type,
            'scanned_at' => now(),
            'latitude'   => $data['latitude']  ?? null,
            'longitude'  => $data['longitude'] ?? null,
            'accuracy'   => $data['accuracy']  ?? null,
            'distance_m' => $fence['distance'],
            'method'     => 'qr',
            'ip_address' => $request->ip(),
            'user_agent' => substr((string) $request->userAgent(), 0, 512),
        ]);

        $summary = $this->status->summarise($staff, $today, $existing->push($record));

        $message = $type === 'in'
            ? 'Checked in at ' . $record->scanned_at->format('g:i A') . ' - ' . strtolower($summary['status']) . '.'
            : 'Checked out at ' . $record->scanned_at->format('g:i A') . '.';

        // A scan that skipped the distance check must never read like one
        // that passed it. The row is real; how it got here is not.
        if (!empty($fence['skipped'])) {
            $message .= $fence['distance'] !== null
                ? " (Geofence off for testing - you were {$fence['distance']} m from the museum.)"
                : ' (Geofence off for testing.)';
        }

        return response()->json([
            'ok'      => true,
            'type'    => $type,
            'time'    => $record->scanned_at->format('g:i A'),
            'status'  => $summary['status'],
            'message' => $message,
        ]);
    }

    // -- Oversight board ---------------------------------------------------

    public function index(Request $request)
    {
        $date = $request->filled('date')
            ? Carbon::parse($request->input('date'))
            : today();

        $board = $this->status->boardFor($date);

        return view('staff-attendance.index', [
            'date'   => $date,
            'board'  => $board,
            'counts' => [
                'present' => $board->where('status', AttendanceStatusService::PRESENT)->count(),
                'late'    => $board->where('status', AttendanceStatusService::LATE)->count(),
                'absent'  => $board->where('status', AttendanceStatusService::ABSENT)->count(),
                'manual'  => $board->where('is_manual', true)->count(),
            ],
            'pendingCorrections' => AttendanceCorrection::where('status', 'Pending')->count(),
        ]);
    }

    /** One staff member's month, and the source of the printed DTR. */
    public function show(Request $request, Staff $staff)
    {
        $this->abortIfNotMuseumStaff($staff);

        $month = $request->filled('month')
            ? Carbon::parse($request->input('month') . '-01')
            : today()->startOfMonth();

        $from = $month->copy()->startOfMonth();
        $to   = $month->copy()->endOfMonth();

        // Never project a DTR into the future.
        if ($to->isFuture()) {
            $to = today();
        }

        $days = $this->status->rangeFor($staff, $from, $to);

        return view('staff-attendance.show', [
            'staff'  => $staff,
            'month'  => $month,
            'days'   => $days,
            'totals' => $this->totals($days),
        ]);
    }

    /**
     * The Tourism office has no attendance record to look at or schedule to
     * set — she works from the municipal office and never clocks in. Hitting
     * one of those URLs with her id is a mistake, not a permission problem,
     * so it 404s rather than 403s.
     */
    private function abortIfNotMuseumStaff(Staff $staff): void
    {
        abort_unless($staff->role === Staff::ROLE_ADMIN, 404);
    }

    private function totals($days): array
    {
        return [
            'present' => $days->where('status', AttendanceStatusService::PRESENT)->count(),
            'late'    => $days->where('status', AttendanceStatusService::LATE)->count(),
            'absent'  => $days->where('status', AttendanceStatusService::ABSENT)->count(),
            'manual'  => $days->where('is_manual', true)->count(),
            'minutes' => $days->sum('worked_minutes'),
        ];
    }

    // -- Schedules (Tourism office only) -----------------------------------

    public function schedules(Staff $staff)
    {
        $this->abortIfNotMuseumStaff($staff);

        $staff->load('schedules');

        return view('staff-attendance.schedule', [
            'staff'     => $staff,
            'schedules' => $staff->schedules->keyBy('weekday'),
        ]);
    }

    public function saveSchedules(Request $request, Staff $staff)
    {
        $this->abortIfNotMuseumStaff($staff);

        $data = $request->validate([
            'days'                 => 'required|array',
            'days.*.is_rest_day'   => 'nullable|boolean',
            'days.*.shift_start'   => 'nullable|date_format:H:i',
            'days.*.shift_end'     => 'nullable|date_format:H:i',
            'days.*.grace_minutes' => 'nullable|integer|min:0|max:120',
        ]);

        foreach ($data['days'] as $weekday => $row) {
            $weekday = (int) $weekday;
            if ($weekday < 0 || $weekday > 6) continue;

            $isRest = (bool) ($row['is_rest_day'] ?? false);

            // A working day needs both ends of the shift, or "late" is undefined.
            if (!$isRest && (empty($row['shift_start']) || empty($row['shift_end']))) {
                StaffSchedule::where('staff_id', $staff->staff_id)->where('weekday', $weekday)->delete();
                continue;
            }

            StaffSchedule::updateOrCreate(
                ['staff_id' => $staff->staff_id, 'weekday' => $weekday],
                [
                    'shift_start'   => $isRest ? '00:00' : $row['shift_start'],
                    'shift_end'     => $isRest ? '00:00' : $row['shift_end'],
                    'grace_minutes' => (int) ($row['grace_minutes'] ?? 15),
                    'is_rest_day'   => $isRest,
                ]
            );
        }

        Log::create([
            'user_id'    => auth()->id(),
            'user_name'  => auth()->user()->name,
            'role'       => auth()->user()->role,
            'action'     => 'Schedule Updated',
            'details'    => "Set work schedule for {$staff->name}",
            'ip_address' => request()->ip(),
        ]);

        return back()->with('success', "Schedule saved for {$staff->name}.");
    }
}
